#.travis.yml
language: node_js

node_js:
  - "6.9"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - sshpass

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod

after_success:
  - sshpass -p $scpPass scp -r -o StrictHostKeyChecking=no ./dist/* root@pacecouriers.com:/usr/share/nginx/quantumex.ca/

notifications:
  email:
    on_failure: tanzeelrana901223@gmail.com
    on_success: tanzeelrana901223@gmail.com